### ISSUE TITLE
New release required for Python 3.7 compatibility

### ISSUE THREAD

**Issue by kalaspuff** [Polyconseil/aioamqp#168]
With the upcoming Python 3.7 release and now when Python 3.7rc1 is available it would be great to have an `aioamqp` release that includes the commit for Python 3.7 support (https://github.com/Polyconseil/aioamqp/commit/d35011900ae52904ac36326533ba43974a637a6a) as `async` and `await` now will be reserved keywords.

**Error in aioamqp==0.10.0**
```bash
ede240405a6b:/# pip install aioamqp
Collecting aioamqp
  Using cached https://files.pythonhosted.org/packages/90/73/96561edbc743e8f95f55ce8852d40bac8b413857b273a625321de8f0143d/aioamqp-0.10.0-py33.py34.py35-none-any.whl
Installing collected packages: aioamqp
Successfully installed aioamqp-0.10.0

ede240405a6b:/# python
Python 3.7.0rc1 (default, Jun 13 2018, 09:19:31) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aioamqp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/aioamqp/__init__.py", line 8, in <module>
    from .protocol import AmqpProtocol
  File "/usr/local/lib/python3.7/site-packages/aioamqp/protocol.py", line 13, in <module>
    from .compat import ensure_future
  File "/usr/local/lib/python3.7/site-packages/aioamqp/compat.py", line 11
    ensure_future = asyncio.async
                                ^
SyntaxError: invalid syntax
>>> 
```

**Fixed in master**
```bash
ede240405a6b:/# pip install git+ssh://git@github.com/Polyconseil/aioamqp.git
Collecting git+ssh://git@github.com/Polyconseil/aioamqp.git
  Cloning ssh://git@github.com/Polyconseil/aioamqp.git to /tmp/pip-req-build-ubfxh2fx
Installing collected packages: aioamqp
  Running setup.py install for aioamqp ... done
Successfully installed aioamqp-0.10.0

ede240405a6b:/# python
Python 3.7.0rc1 (default, Jun 13 2018, 09:19:31) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aioamqp
>>> 
```

**Comment by diogommartins** [comment]
@dzen  Master seems stable. Could you create a new release? =)

**Comment by dzen** [comment]
Sorry, I just uploaded a new release.

https://pypi.org/project/aioamqp/

**Comment by diogommartins** [comment]
Yay ! Thanks a lot =)
