### ISSUE TITLE
AmazonMQ issues on `queue_declare`

### ISSUE THREAD

**Issue by cacciald-scoutbee** [Polyconseil/aioamqp#230]
Hi I'm receiving the following error when trying to declare a queue in a vhost inside an AmazonMQ (RabbitMQ 3.8.26) installation:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/aioamqp_consumer/amqp.py", line 12, in wrapper
    return await fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/aioamqp_consumer/amqp.py", line 56, in _connect
    **kwargs,
  File "/home/user/.local/lib/python3.7/site-packages/aioamqp/__init__.py", line 102, in from_url
    **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/aioamqp/__init__.py", line 63, in connect
    insist=insist)
  File "/home/user/.local/lib/python3.7/site-packages/aioamqp/protocol.py", line 196, in start_connection
    await self.dispatch_frame()
  File "/home/user/.local/lib/python3.7/site-packages/aioamqp/protocol.py", line 264, in dispatch_frame
    frame_channel, frame = await self.get_frame()
  File "/home/user/.local/lib/python3.7/site-packages/aioamqp/protocol.py", line 251, in get_frame
    return await amqp_frame.read(self._stream_reader)
  File "/home/user/.local/lib/python3.7/site-packages/aioamqp/frame.py", line 84, in read
    payload_data = await reader.readexactly(frame_length)
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
ConnectionResetError: [Errno 104] Connection reset by peer
```

I'm suspecting it is related somehow to SSL configuration but can't find the reason TBH. Locally with the sam rabbitMQ version and without SSL works perfectly. Any hint or idea on how to proceed or is this a known issue of the library?

PS: No relevant logs in the rabbit side.

**Comment by cacciald-scoutbee** [comment]
It was ssl and I think I have fixed it... Thanks to the PR #213 any idea when this will be merged and fixed because it seems a pretty rational behaviour
